name: Package using PyInstaller
on:
  push:
    branches: 
      - github-actions
  workflow_dispatch:

jobs:
  build-windows:
    env:
      dist-path: dist/OpenSeeFace
    runs-on: windows-latest
    steps:
      - name: Pull OpenSeeFace
        uses: actions/checkout@v4

      - name: Create binary
        shell: cmd
        run: |
          choco install vcredist140

          xcopy c:\Windows\System32\msvcp140.dll .
          xcopy c:\Windows\System32\vcomp140.dll .
          xcopy c:\Windows\System32\concrt140.dll .
          xcopy c:\Windows\System32\vccorlib140.dll .

          make_exe.bat

      - name: Move files for uploading
        shell: bash
        run: |
          # Prevents the parent dist/ directory from being included
          mv dist/facetracker ${{ env.dist-path }}
          cp -r models ${{ env.dist-path }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenSeeFace-windows
          path: dist/OpenSeeFace

  # Files must be packed into a tar in order for file permissions to be preserved
  build-unix:
    env:
      artifact-path: OpenSeeFace
      tar-path: OpenSeeFace.tar
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Pull OpenSeeFace
        uses: actions/checkout@v4

      - name: Create binary
        shell: bash
        run: |
          chmod +x make_exe.sh
          ./make_exe.sh

      - name: Move files for uploading
        shell: bash
        run: |
          # Prevents the parent dist/ directory from being included
          mv dist/facetracker ${{ env.artifact-path }}
          cp -r models ${{ env.artifact-path }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenSeeFace-${{ matrix.name }}
          path: ${{ env.artifact-path }}
